// Shared domain types. The backend is not live yet, so these shapes are the
// contract sampleData.ts and the (future) API layer both agree to honor.

export type ContributionStatus = 'paid' | 'pending' | 'late';

export type MemberRole = 'organizer' | 'member';

export type GroupFrequency = 'weekly' | 'monthly';

export interface User {
  id: string;
  name: string;
  phone: string;
  email: string;
  avatarUrl?: string;
  /** Cloudinary URL of the profile photo (susutrack/profiles/). */
  profilePhotoUrl?: string;
  idVerified: boolean;
  /** True once ID + selfie were submitted, even if review is still pending. */
  idSubmitted?: boolean;
  reliabilityScore: number; // 0-100
  streak: number; // consecutive cycles paid on time
  penaltyDebt: number; // GHS owed in penalties
  arrears: number; // GHS owed in missed contributions
  /** ISO timestamp of T&C acceptance, stored server-side in the users table. */
  tcAcceptedAt?: string;
}

export interface GroupMember {
  id: string;
  userId: string;
  name: string;
  avatarUrl?: string;
  role: MemberRole;
  status: ContributionStatus;
  progressPct: number; // 0-100, how much of this cycle's contribution is paid
  reliabilityScore: number; // 0-100
  penaltyDebt: number;
  streak?: number; // consecutive on-time cycles (drives StreakBadge)
  /** Removed by admin — shows a grey "Removed" chip and is blocklisted from rejoining. */
  removed?: boolean;
}

export interface JoinRequest {
  id: string;
  userId: string;
  name: string;
  idVerified: boolean;
  /** Reliability carried over from the member's other groups; undefined = new user. */
  reliabilityScore?: number;
  requestedAt: string; // ISO date
}

export interface RotationEntry {
  position: number;
  memberId: string;
  memberName: string;
  date: string; // ISO date
  amount: number;
  state: 'completed' | 'current' | 'upcoming';
  collectedCount?: number;
  totalCount?: number;
  reliabilityScore?: number;
}

export interface CycleHistoryEntry {
  cycle: number;
  recipientName: string;
  amount: number;
  date: string;
  completed: boolean;
}

export interface Group {
  id: string;
  name: string;
  description: string;
  cycle: number;
  totalCycles: number;
  status: 'open' | 'closed';
  contributionAmount: number;
  frequency: GroupFrequency;
  collected: number;
  expected: number;
  nextContributionInHours: number;
  currentRecipientId: string;
  currentRecipientName: string;
  currentRecipientAvatar?: string;
  memberCount: number;
  maxMembers: number;
  role: MemberRole;
  progressPct: number;
  members: GroupMember[];
  rotation: RotationEntry[];
  history: CycleHistoryEntry[];
  payoutFrozen: boolean;
  freezeReason?: string;
  /** SUSU-XXXXXX code generated by the backend at group creation. */
  inviteCode: string;
  adminName: string;
  penaltyFee: number; // GHS per late cycle, 0 = none
  gracePeriodDays: number;
  rules?: string;
  /** False until cycle 1 opens — rotation order is drag-to-reorder while false. */
  cycleStarted: boolean;
  pendingRequests: JoinRequest[];
}

/** Public preview returned by GET /api/groups/preview/:inviteCode (no auth). */
export interface GroupPreview {
  id: string;
  name: string;
  contributionAmount: number;
  frequency: GroupFrequency;
  slotsRemaining: number;
  adminName: string;
  rules: string;
}

export type ActivityType = 'payment' | 'member_joined' | 'payout_started' | 'alert';

export interface ActivityItem {
  id: string;
  type: ActivityType;
  title: string;
  subtitle: string;
  timestamp: string;
}

export type NotificationType = 'payment' | 'payout' | 'warning' | 'info' | 'overdue' | 'reminder';

export interface AppNotification {
  id: string;
  type: NotificationType;
  title: string;
  body: string;
  timestamp: string;
  read: boolean;
}

export interface ContributionHistoryItem {
  id: string;
  label: string;
  date: string;
  amount: number;
}

/** Earned streak badges — thresholds documented in StreakBadge.tsx. */
export type StreakTier = 'reliable' | 'trusted' | 'champion';
